### PR TITLE
New design

### PR DESCRIPTION
**Pull request by daliborjanak**
Design improvements, mobile responsive fixes and general update of the layout.
I hope this can finish the first production version of this website. We would like to switch the original Wordpress with this Jekyll site to open easy contributing to everyone

### CODE REVIEW

**Comment by SomeoneElseOSM** [comment]
Can you perhaps explain in a bit more detail (with words) what you are actually trying to do?

**Comment by daliborjanak** [comment]
Yes, sorry for the short description. 
I like the idea of this project so we created a new design for the website http://switch2osm.github.io/. It is responsive ready, we didn't change the content - just styles, layouts and necessary movings. You can see it live from our fork:
https://klokantech.github.io/switch2osm/
We would like to see it deployed at least on http://switch2osm.github.io/

After that, we would like to also switch domain https://switch2osm.org/ to use this repo instead of Wordpress. I don't know who is maintaining it but it is not possible to update content in Wordpress easily or send the suggestions for updates.

**Comment by ThomasG77** [comment]
Hi,

Wondering how you manage translation? I've done the translation to French on original Wordpress.
No multi language management seems to be a regression although the look and feel has been updated.

**Comment by daliborjanak** [comment]
It is not easy to create multilingual pages with Jekyll/gh-pages. We are doing it with data files and multiple markdown pages and on own deployment. This PR doesn't do that as you are mentioning. It just fixes style and design of Jekyll sites on https://switch2osm.github.io/

**Comment by ThomasG77** [comment]
@SomeoneElseOSM @pnorman Any opinion on merging?

**Comment by pnorman** [comment]
> Any opinion on merging?

I am no longer involved in the switch2osm site. If technical help is needed I can offer some, but I have limited time.

**Comment by klokan** [comment]
Hi everybody!

This PR brings a new responsive design without any other change. No strings attached 😉

The design with green elements is visually aligned to the style of existing pages such as https://www.openstreetmap.org/about and https://learnosm.org/en/.

It is our contribution to the OSM - without expectation of anything back. 🎁

We give up all the rights - and provide this work as Public Domain - for the good of OpenStreetMap community. You did a lot already and we are keen to give back and help.

Localization and Transifex support a la https://github.com/hotosm/learnosm can be added in a separate PR.

https://switch2osm.org/ is dating and should be switched from WordPress to Github Pages (which is why this repo was created, right?). We hope this PR can help to move things again...

It can be relatively easy to merge it (only a small change in config.yaml is required) - and switch the domain to GitHub hosting - and continue on other improvements as people find time...

**Comment by klokan** [comment]
BTW If you have suggestions for improvement of the design - we are listening and would be happy to alter the code further (if time allows).

I see we missed to port the slider (have not seen it initially, was it there about a year ago?).

What about presenting the "benefits" with relevant texts such as:
- Rich data
- Up to date
- Tune your experience
- Global data
- No licensing fee

Always on background - where the map is now and the static title "Take back control of your maps" appears? Perhaps there can be also some "<" and ">" buttons for switching.

Screenshot 2019-10-31 at 13 06 41
Screenshot 2019-10-31 at 13 06 30
Screenshot 2019-10-31 at 13 05 34
Screenshot 2019-10-31 at 13 05 04
Screenshot 2019-10-31 at 13 04 51


On different pages, it can be a random message from the list above (not always the "Rich data").

Screenshot 2019-10-31 at 12 46 27

**Comment by SomeoneElseOSM** [comment]
> 
> 
> @SomeoneElseOSM Sorry to bother again: an opinion? Otherwise, will take the responsibility to merge.

I would have been concerned about the loss of translations, but I've just looked and the only translation I can see is French and it is some years out of date, so that isn't a blocker.

@systemed Any thoughts?

**Comment by systemed** [comment]
This looks superb.

**Comment by SomeoneElseOSM** [comment]
Thanks.  I'm somewhat concerned by the "1 check failed" above so I'll fight my way through building it from scratch at some point (no promises when though) to see if anything else crawls out of the woodwork before recommending to whoever looks after switch2osm.org to switch over.

**Comment by ThomasG77** [comment]
At the moment, only fixing issues to see the website display well from http://switch2osm.github.io (broken)

**Comment by ThomasG77** [comment]
Fixing done everywhere with #61, #62 and one commit (https://github.com/switch2osm/switch2osm.github.io/commit/70944887bd6cffa27581baf02e1b20859ef5e651) to remove trailing slash in configuration to avoid getting URLs with double slash in links e.g https://switch2osm.github.io//using-tiles/ (I didn't consider making a PR here was needed)
Make feedback about broken links, wrong paths,...

**Comment by SomeoneElseOSM** [comment]
>  Make feedback about any other issues you think related

I'm not sure exactly what you mean by that.  Are you asking people to create new issues about any wrong links that they find and that you will then fix them?

**Comment by ThomasG77** [comment]
> Are you asking people to create new issues about any wrong links that they find and that you will then fix them?

This sentence was in case if I've missed a fix but from my tests, there are no broken links now.
Undoing is not necessary.

**Comment by SomeoneElseOSM** [comment]
@ThomasG77 Great - thanks.

**Pull request merged**
