### PR TITLE
Conf -> mods on ubuntu 20.04

### PR DESCRIPTION
**Pull request by stalker314314**
At least, this is what my Apache2 needs

### CODE REVIEW

**Comment by SomeoneElseOSM** [comment]
It's entirely possible that both will work, or that something has changed.  The former certainly worked for me when I did a test as part of writing it back in May:

    /etc/apache2/conf-available:
    total used in directory 36 available 30290036
    drwxr-xr-x 2 root root 4096 May  3 21:22 .
    -rw-r--r-- 1 root root   60 May  3 21:22 mod_tile.conf

What error did you get?

**Comment by stalker314314** [comment]
Working situation:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
$ apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-04-13T17:19:17
$ ls /etc/apache2/conf-available/
charset.conf  javascript-common.conf  localized-error-pages.conf  mod_tile.conf  munin.conf  other-vhosts-access-log.conf  security.conf  serve-cgi-bin.conf
$ ls /etc/apache2/mods-available/
access_compat.load  authz_core.load       cgid.load          file_cache.load           log_debug.load     proxy.conf           proxy_wstunnel.load  socache_memcache.load
actions.conf        authz_dbd.load        charset_lite.load  filter.load               log_forensic.load  proxy.load           ratelimit.load       socache_redis.load
actions.load        authz_dbm.load        data.load          headers.load              lua.load           proxy_ajp.load       reflector.load       socache_shmcb.load
alias.conf          authz_groupfile.load  dav.load           heartbeat.load            macro.load         proxy_balancer.conf  remoteip.load        speling.load
alias.load          authz_host.load       dav_fs.conf        heartmonitor.load         md.load            proxy_balancer.load  reqtimeout.conf      ssl.conf
allowmethods.load   authz_owner.load      dav_fs.load        http2.conf                mime.conf          proxy_connect.load   reqtimeout.load      ssl.load
asis.load           authz_user.load       dav_lock.load      http2.load                mime.load          proxy_express.load   request.load         status.conf
auth_basic.load     autoindex.conf        dbd.load           ident.load                mime_magic.conf    proxy_fcgi.load      rewrite.load         status.load
auth_digest.load    autoindex.load        deflate.conf       imagemap.load             mime_magic.load    proxy_fdpass.load    sed.load             substitute.load
auth_form.load      brotli.load           deflate.load       include.load              mod_tile.load      proxy_ftp.conf       session.load         suexec.load
authn_anon.load     buffer.load           dialup.load        info.conf                 mpm_event.conf     proxy_ftp.load       session_cookie.load  unique_id.load
authn_core.load     cache.load            dir.conf           info.load                 mpm_event.load     proxy_hcheck.load    session_crypto.load  userdir.conf
authn_dbd.load      cache_disk.conf       dir.load           lbmethod_bybusyness.load  mpm_prefork.conf   proxy_html.conf      session_dbd.load     userdir.load
authn_dbm.load      cache_disk.load       dump_io.load       lbmethod_byrequests.load  mpm_prefork.load   proxy_html.load      setenvif.conf        usertrack.load
authn_file.load     cache_socache.load    echo.load          lbmethod_bytraffic.load   mpm_worker.conf    proxy_http.load      setenvif.load        vhost_alias.load
authn_socache.load  cern_meta.load        env.load           lbmethod_heartbeat.load   mpm_worker.load    proxy_http2.load     slotmem_plain.load   xml2enc.load
authnz_fcgi.load    cgi.load              expires.load       ldap.conf                 negotiation.conf   proxy_scgi.load      slotmem_shm.load
authnz_ldap.load    cgid.conf             ext_filter.load    ldap.load                 negotiation.load   proxy_uwsgi.load     socache_dbm.load
```

When I did as per instructions (creating `.conf` file in `conf-available`), I got:
```
$ sudo a2enmod mod_tile
ERROR: Module mod_tile does not exist!
```

**Comment by SomeoneElseOSM** [comment]
Odd, still "works for me".  I've just followed https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/ again and it just worked - no need to change anything.

user@server:/var/www/html$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
user@server:/var/www/html$ apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17
user@server:/var/www/html$ ls /etc/apache2/conf-available/
charset.conf            localized-error-pages.conf  munin.conf                    security.conf
javascript-common.conf  mod_tile.conf               other-vhosts-access-log.conf  serve-cgi-bin.conf
user@server:/var/www/html$ ls /etc/apache2/mods-available/
access_compat.load    cache.load          heartmonitor.load         negotiation.conf     session.load
actions.conf          cache_disk.conf     http2.conf                negotiation.load     session_cookie.load
actions.load          cache_disk.load     http2.load                proxy.conf           session_crypto.load
alias.conf            cache_socache.load  ident.load                proxy.load           session_dbd.load
alias.load            cern_meta.load      imagemap.load             proxy_ajp.load       setenvif.conf
allowmethods.load     cgi.load            include.load              proxy_balancer.conf  setenvif.load
asis.load             cgid.conf           info.conf                 proxy_balancer.load  slotmem_plain.load
auth_basic.load       cgid.load           info.load                 proxy_connect.load   slotmem_shm.load
auth_digest.load      charset_lite.load   lbmethod_bybusyness.load  proxy_express.load   socache_dbm.load
auth_form.load        data.load           lbmethod_byrequests.load  proxy_fcgi.load      socache_memcache.load
authn_anon.load       dav.load            lbmethod_bytraffic.load   proxy_fdpass.load    socache_redis.load
authn_core.load       dav_fs.conf         lbmethod_heartbeat.load   proxy_ftp.conf       socache_shmcb.load
authn_dbd.load        dav_fs.load         ldap.conf                 proxy_ftp.load       speling.load
authn_dbm.load        dav_lock.load       ldap.load                 proxy_hcheck.load    ssl.conf
authn_file.load       dbd.load            log_debug.load            proxy_html.conf      ssl.load
authn_socache.load    deflate.conf        log_forensic.load         proxy_html.load      status.conf
authnz_fcgi.load      deflate.load        lua.load                  proxy_http.load      status.load
authnz_ldap.load      dialup.load         macro.load                proxy_http2.load     substitute.load
authz_core.load       dir.conf            md.load                   proxy_scgi.load      suexec.load
authz_dbd.load        dir.load            mime.conf                 proxy_uwsgi.load     unique_id.load
authz_dbm.load        dump_io.load        mime.load                 proxy_wstunnel.load  userdir.conf
authz_groupfile.load  echo.load           mime_magic.conf           ratelimit.load       userdir.load
authz_host.load       env.load            mime_magic.load           reflector.load       usertrack.load
authz_owner.load      expires.load        mpm_event.conf            remoteip.load        vhost_alias.load
authz_user.load       ext_filter.load     mpm_event.load            reqtimeout.conf      xml2enc.load
autoindex.conf        file_cache.load     mpm_prefork.conf          reqtimeout.load
autoindex.load        filter.load         mpm_prefork.load          request.load
brotli.load           headers.load        mpm_worker.conf           rewrite.load
buffer.load           heartbeat.load      mpm_worker.load           sed.load

**Comment by codydaig** [comment]
Confirming that `conf-available` also worked for me as expected in the directions.

**Comment by SomeoneElseOSM** [comment]
I'll close this since no-one can reproduce the error (yet).

**Pull request closed without merging**
