### PR TITLE
add OSMUK Talent Directory to service providers

### LINKED ISSUE #76: add OSMUK Talent Director to Providers list
The OSMUK Local Chapter run a "Talent Directory" where UK companies can be put in touch with UK OSM service providers. https://osmuk.org/professional-services/

Please add to the Providers list of the UK.

### PR DESCRIPTION
**Pull request by jnicho02**
fixes #76

If other Local Chapters start to do the same thing then we might want to consider promoting them ahead of private companies...but that's for the future.

### CODE REVIEW

**Comment by SomeoneElseOSM** [comment]
I may be missing something, but the page at https://osmuk.org/professional-services/ seems to be mostly content-free at the moment?

**Comment by jnicho02** [comment]
Succinct != content-free

The page offers UK businesses and organisations to contact the Local Chapter with requirements in order to be put in touch with UK service providers. It outlines the process, and invites UK service providers to join.

**Comment by ThomasG77** [comment]
How is it different from https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services ? If I want a list of professionals, I go to above page or look at https://switch2osm.org to get directly companies. Do we want to reference another third party list of OSM providers in the page because there are specific to an area (UK here)?

**Comment by jnicho02** [comment]
You know what, I don't need to defend the actions of the OSM UK Local Chapter to you.

I'm really pleased that switch2osm has been updated and we will happily point people toward it. I look forward to the day when it works so well that companies do not need a human to talk to. In the meantime, we will continue to talk to them and generate opportunities for local mappers.

**Comment by atomoil** [comment]
> I may be missing something, but the page at https://osmuk.org/professional-services/ seems to be mostly content-free at the moment?

@SomeoneElseOSM we're always interested in feedback on improving the Talent Directory, so it would be really great if you were able to expand on your point - is that possible? I'm particularly interested in anything you think we should add or remove from the page. 

I realise this message is not strictly related to this PR, so don't hesitate to let me know if you'd rather discuss on another channel.

**Comment by SomeoneElseOSM** [comment]
@atomoil The comment that I wrote yesterday on the issue at https://github.com/switch2osm/switch2osm.github.io/issues/76#issuecomment-562857752 provides a bit more detail.  Not having seen it before I was expecting your page to be a list of providers, which it isn't.  As I said there, 
there's definitely a case for pointing people who come to switch2osm at OSM community resources, Depending on who they are and where they're from an appropriate place might be OSMF's US-focused "Welcome Mat", or "openstreetmap.community", or a specific community resource or local chapter.   That would be a new page that no-one has written yet, though.

**Comment by atomoil** [comment]
@SomeoneElseOSM thanks for clarifying, I understand your point much better - the Talent Directory is absolutely not just a list of providers, (as noted those already exist), it's very much a personalised service designed to help and guide businesses and organisations who want to engage with OSM and connect them with experts who can fulfil their project needs.

I would still be interested if you have any specific feedback / suggestions for improvements regarding the Talent Directory, as on the comment you reference you said:
> The problem with the OSM UK page is that it's a vague "come and talk to us" one. It's exactly the sort of page that if I was buying for $dayjob or even just trying to call a plumber I'd avoid.

Is this because the Talent Directory approach isn't of interest to you or is there anything on the page we could improve that would make this more attractive to you?

**Comment by SomeoneElseOSM** [comment]
> Is this because the Talent Directory approach isn't of interest to you or is there anything on the page we could improve that would make this more attractive to you?

To pick 3 at random from the current providers listing, https://www.maptiler.com/ , https://www.and.com/services-3/map-hosting/ and https://www.systemed.net/openstreetmap/ all say "we can do X" or "in the past we helped people with X" not just "come and talk to us".  In order to be useful as a "talent directory", it has to at the very least be a "directory".  https://osmuk.org/professional-services/ has no details of who my details would be passed on to if I have a requirement or what they are capable of doing; https://osmuk.org/use-osm/ has a bit more information, but nothing on there suggests it was developed by anyone on the list (my guess is that at least 2 of the "view the map" examples will be by people who are).

**Comment by atomoil** [comment]
@SomeoneElseOSM Thanks so much, that’s very useful feedback. 😎

And thanks to everyone else for their patience while I hijacked a closed PR thread. 😬

**Pull request closed without merging**
